-- National-Dex keyed mount data. Renderer-specific anchors and art do not
-- belong here; this file is gameplay data only.

return {
  defaults = {
    ground = { speed = 1.35, acceleration = 0.20, braking = 0.26,
      launch = 0.72, turnRate = 0.92, boost = 2.00 },
    surf = { speed = 1.15, acceleration = 0.16, braking = 0.18,
      launch = 0.76, turnRate = 0.88, boost = 2.00 },
    flight = { speed = 1.50, acceleration = 0.14, braking = 0.14,
      launch = 0.80, turnRate = 0.84, boost = 2.00,
      verticalSpeed = 0.65 },
  },
  mounts = {
    -- heightM mirrors the species' Pokédex height. MountScale converts it to
    -- a compact overworld footprint with a square-root curve: long-bodied
    -- species remain visibly larger without occupying half the screen.
    { dex = 6, species = "CHARIZARD", heightM = 1.7, modes = { "flight" },
      movement = { flight = { speed = 1.58, acceleration = 0.18,
        turnRate = 0.88, verticalSpeed = 0.72 } } },
    { dex = 9, species = "BLASTOISE", heightM = 1.6, modes = { "surf" },
      movement = { surf = { speed = 1.08 } } },
    { dex = 18, species = "PIDGEOT", heightM = 1.5, modes = { "flight" },
      movement = { flight = { speed = 1.48 } } },
    { dex = 22, species = "FEAROW", heightM = 1.2, modes = { "flight" },
      movement = { flight = { speed = 1.60 } } },
    { dex = 42, species = "GOLBAT", heightM = 1.6, modes = { "flight" },
      movement = { flight = { speed = 1.44 } } },
    { dex = 59, species = "ARCANINE", heightM = 1.9, modes = { "ground" },
      movement = { ground = { speed = 1.52, acceleration = 0.26,
        braking = 0.30, turnRate = 0.94 } } },
    { dex = 73, species = "TENTACRUEL", heightM = 1.6, modes = { "surf" },
      movement = { surf = { speed = 1.36 } } },
    { dex = 77, species = "RAPIDASH", heightM = 1.7, modes = { "ground" },
      movement = { ground = { speed = 1.65 } } },
    { dex = 85, species = "DODRIO", heightM = 1.8, modes = { "ground" },
      movement = { ground = { speed = 1.70 } } },
    { dex = 111, species = "RHYHORN", heightM = 1.0, modes = { "ground" },
      movement = { ground = { speed = 0.88, acceleration = 0.10,
        braking = 0.42, launch = 0.58, turnRate = 0.68 } } },
    { dex = 112, species = "RHYDON", heightM = 1.9, modes = { "ground" },
      movement = { ground = { speed = 1.00 } } },
    { dex = 115, species = "KANGASKHAN", heightM = 2.2,
      modes = { "ground" }, movement = { ground = { speed = 1.44 } } },
    { dex = 128, species = "TAUROS", heightM = 1.4, modes = { "ground" },
      movement = { ground = { speed = 1.68 } } },
    { dex = 130, species = "GYARADOS", heightM = 6.5, modes = { "surf" },
      movement = { surf = { speed = 1.18 } } },
    { dex = 131, species = "LAPRAS", heightM = 2.5, modes = { "surf" },
      movement = { surf = { speed = 1.24, acceleration = 0.20,
        turnRate = 0.92 } } },
    { dex = 142, species = "AERODACTYL", heightM = 1.8,
      modes = { "flight" }, movement = { flight = { speed = 1.90,
        acceleration = 0.23, turnRate = 0.90, verticalSpeed = 0.88 } } },
    { dex = 143, species = "SNORLAX", heightM = 2.1, modes = { "ground" },
      movement = { ground = { speed = 0.82 } } },
    { dex = 144, species = "ARTICUNO", heightM = 1.7, modes = { "flight" },
      movement = { flight = { speed = 1.38 } } },
    { dex = 145, species = "ZAPDOS", heightM = 1.6, modes = { "flight" },
      movement = { flight = { speed = 1.62 } } },
    { dex = 146, species = "MOLTRES", heightM = 2.0, modes = { "flight" },
      movement = { flight = { speed = 1.46 } } },
    { dex = 148, species = "DRAGONAIR", heightM = 4.0,
      modes = { "flight" }, movement = { flight = { speed = 1.22 } } },
    { dex = 149, species = "DRAGONITE", heightM = 2.2,
      modes = { "flight" }, movement = { flight = { speed = 1.34 } } },
    { dex = 154, species = "MEGANIUM", heightM = 1.8,
      modes = { "ground" }, movement = { ground = { speed = 1.30 } } },
    { dex = 160, species = "FERALIGATR", heightM = 2.3, modes = { "surf" },
      movement = { surf = { speed = 1.30 } } },
    { dex = 164, species = "NOCTOWL", heightM = 1.6, modes = { "flight" },
      movement = { flight = { speed = 1.18 } } },
    { dex = 169, species = "CROBAT", heightM = 1.8, modes = { "flight" },
      movement = { flight = { speed = 1.92 } } },
    { dex = 178, species = "XATU", heightM = 1.5, modes = { "flight" },
      movement = { flight = { speed = 1.52 } } },
    { dex = 203, species = "GIRAFARIG", heightM = 1.5,
      modes = { "ground" }, movement = { ground = { speed = 1.36 } } },
    { dex = 217, species = "URSARING", heightM = 1.8,
      modes = { "ground" }, movement = { ground = { speed = 1.13 } } },
    { dex = 226, species = "MANTINE", heightM = 2.1, modes = { "surf" },
      movement = { surf = { speed = 1.55 } } },
    { dex = 227, species = "SKARMORY", heightM = 1.7,
      modes = { "flight" }, movement = { flight = { speed = 1.20 } } },
    { dex = 230, species = "KINGDRA", heightM = 1.8, modes = { "surf" },
      movement = { surf = { speed = 1.42 } } },
    { dex = 232, species = "DONPHAN", heightM = 1.1, modes = { "ground" },
      movement = { ground = { speed = 1.08 } } },
    { dex = 234, species = "STANTLER", heightM = 1.4,
      modes = { "ground" }, movement = { ground = { speed = 1.38 } } },
    { dex = 243, species = "RAIKOU", heightM = 1.9, modes = { "ground" },
      movement = { ground = { speed = 1.78 } } },
    { dex = 244, species = "ENTEI", heightM = 2.1, modes = { "ground" },
      movement = { ground = { speed = 1.60 } } },
    {
      dex = 245,
      species = "SUICUNE",
      heightM = 2.0,
      modes = { "ground", "surf" },
      movement = {
        ground = { speed = 1.46 },
        surf = { speed = 1.48 },
      },
      traits = { amphibious = true },
    },
    { dex = 248, species = "TYRANITAR", heightM = 2.0,
      modes = { "ground" }, movement = { ground = { speed = 1.18 } } },
    { dex = 249, species = "LUGIA", heightM = 5.2,
      modes = { "surf", "flight" },
      movement = {
        surf = { speed = 1.66 },
        flight = { speed = 1.72 },
      } },
    { dex = 250, species = "HO_OH", heightM = 3.8, modes = { "flight" },
      movement = { flight = { speed = 1.42, acceleration = 0.11,
        launch = 0.72, turnRate = 0.76, verticalSpeed = 0.54 } } },
  },
}
