-- National-Dex keyed mount data. Renderer-specific anchors and art do not
-- belong here; this file is gameplay data only.

return {
  defaults = {
    ground = { speed = 1.35, acceleration = 0.20, turnRate = 1.00 },
    surf = { speed = 1.15, acceleration = 0.16, turnRate = 0.90 },
    flight = { speed = 1.50, acceleration = 0.14, turnRate = 0.85 },
  },
  mounts = {
    { dex = 6, species = "CHARIZARD", modes = { "flight" } },
    { dex = 9, species = "BLASTOISE", modes = { "surf" } },
    { dex = 18, species = "PIDGEOT", modes = { "flight" } },
    { dex = 22, species = "FEAROW", modes = { "flight" } },
    { dex = 42, species = "GOLBAT", modes = { "flight" } },
    { dex = 59, species = "ARCANINE", modes = { "ground" } },
    { dex = 73, species = "TENTACRUEL", modes = { "surf" } },
    { dex = 77, species = "RAPIDASH", modes = { "ground" } },
    { dex = 85, species = "DODRIO", modes = { "ground" } },
    { dex = 111, species = "RHYHORN", modes = { "ground" } },
    { dex = 112, species = "RHYDON", modes = { "ground" } },
    { dex = 115, species = "KANGASKHAN", modes = { "ground" } },
    { dex = 128, species = "TAUROS", modes = { "ground" } },
    { dex = 130, species = "GYARADOS", modes = { "surf" } },
    { dex = 131, species = "LAPRAS", modes = { "surf" } },
    { dex = 142, species = "AERODACTYL", modes = { "flight" } },
    { dex = 143, species = "SNORLAX", modes = { "ground" } },
    { dex = 144, species = "ARTICUNO", modes = { "flight" } },
    { dex = 145, species = "ZAPDOS", modes = { "flight" } },
    { dex = 146, species = "MOLTRES", modes = { "flight" } },
    { dex = 148, species = "DRAGONAIR", modes = { "flight" } },
    { dex = 149, species = "DRAGONITE", modes = { "flight" } },
    { dex = 154, species = "MEGANIUM", modes = { "ground" } },
    { dex = 160, species = "FERALIGATR", modes = { "surf" } },
    { dex = 164, species = "NOCTOWL", modes = { "flight" } },
    { dex = 169, species = "CROBAT", modes = { "flight" } },
    { dex = 178, species = "XATU", modes = { "flight" } },
    { dex = 203, species = "GIRAFARIG", modes = { "ground" } },
    { dex = 217, species = "URSARING", modes = { "ground" } },
    { dex = 226, species = "MANTINE", modes = { "surf" } },
    { dex = 227, species = "SKARMORY", modes = { "flight" } },
    { dex = 230, species = "KINGDRA", modes = { "surf" } },
    { dex = 232, species = "DONPHAN", modes = { "ground" } },
    { dex = 234, species = "STANTLER", modes = { "ground" } },
    { dex = 243, species = "RAIKOU", modes = { "ground" } },
    { dex = 244, species = "ENTEI", modes = { "ground" } },
    {
      dex = 245,
      species = "SUICUNE",
      modes = { "ground", "surf" },
      traits = { amphibious = true },
    },
    { dex = 248, species = "TYRANITAR", modes = { "ground" } },
    { dex = 249, species = "LUGIA", modes = { "surf", "flight" } },
    { dex = 250, species = "HO_OH", modes = { "flight" } },
  },
}
